cd ~/go/src/github.com/hacash

1. poolworker
 go build -ldflags '-w -s' -o poolminer_2021-0410.exe miner/run/minerpoolworker/main.go

2. miner
go build -ldflags '-w -s' -o miner_2021_02_12.exe  miner/run/main/main.go

3. cmdwallet
go build -ldflags '-w -s' -o cmdwallet_2021_02_12.exe cmdwallet/run/main/main.go


    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
